# Generated by Django 6.0.5 on 2026-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_name',
            field=models.CharField(blank=True, default='kg', help_text='Unit label at time of order', max_length=50),
        ),
    ]
