# Generated by Django 6.0.5 on 2026-06-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_deliverycluster_deliveryassignment_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_label', models.CharField(help_text="e.g. '7 AM - 12 PM' — stored on orders", max_length=50)),
                ('order_cutoff_time', models.TimeField(help_text='Orders placed before this time get assigned to this slot')),
                ('delivery_start_time', models.TimeField()),
                ('delivery_end_time', models.TimeField()),
                ('assignment_hour', models.PositiveSmallIntegerField(default=6, help_text='Hour (0-23) when auto-assignment runs')),
                ('assignment_minute', models.PositiveSmallIntegerField(default=30, help_text='Minute when auto-assignment runs')),
                ('cleanup_hour', models.PositiveSmallIntegerField(default=12, help_text='Hour (0-23) when cluster cleanup runs')),
                ('cleanup_minute', models.PositiveSmallIntegerField(default=30, help_text='Minute when cluster cleanup runs')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower = processed first in order assignment')),
            ],
            options={
                'verbose_name': 'Delivery Slot',
                'verbose_name_plural': 'Delivery Slots',
                'ordering': ['sort_order', 'order_cutoff_time'],
            },
        ),
    ]
