# Generated by Django 6.0.5 on 2026-06-26 05:29

import datetime
from django.db import migrations


def seed_default_slots(apps, schema_editor):
    DeliverySlot = apps.get_model('orders', 'DeliverySlot')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')

    slots = [
        {
            'name': 'Morning',
            'display_label': '7 AM - 12 PM',
            'order_cutoff_time': datetime.time(12, 0),
            'delivery_start_time': datetime.time(7, 0),
            'delivery_end_time': datetime.time(12, 0),
            'assignment_hour': 6,
            'assignment_minute': 30,
            'cleanup_hour': 12,
            'cleanup_minute': 30,
            'sort_order': 1,
        },
        {
            'name': 'Evening',
            'display_label': '4 PM - 10 PM',
            'order_cutoff_time': datetime.time(22, 0),
            'delivery_start_time': datetime.time(16, 0),
            'delivery_end_time': datetime.time(22, 0),
            'assignment_hour': 15,
            'assignment_minute': 30,
            'cleanup_hour': 22,
            'cleanup_minute': 30,
            'sort_order': 2,
        },
    ]

    for data in slots:
        slot, created = DeliverySlot.objects.update_or_create(
            name=data['name'],
            defaults={k: v for k, v in data.items() if k != 'name'}
        )

        slot_key = slot.name.lower().replace(" ", "-")

        assign_crontab, _ = CrontabSchedule.objects.get_or_create(
            hour=slot.assignment_hour,
            minute=slot.assignment_minute,
            day_of_week='*',
            day_of_month='*',
            month_of_year='*',
        )
        PeriodicTask.objects.update_or_create(
            name=f'auto-assign-{slot_key}',
            defaults={
                'task': 'orders.tasks.run_slot_assignment',
                'crontab': assign_crontab,
                'args': f'["{slot.display_label}"]',
                'enabled': True,
            }
        )

        cleanup_crontab, _ = CrontabSchedule.objects.get_or_create(
            hour=slot.cleanup_hour,
            minute=slot.cleanup_minute,
            day_of_week='*',
            day_of_month='*',
            month_of_year='*',
        )
        PeriodicTask.objects.update_or_create(
            name=f'cleanup-{slot_key}',
            defaults={
                'task': 'orders.tasks.cleanup_slot_clusters',
                'crontab': cleanup_crontab,
                'args': f'["{slot.display_label}"]',
                'enabled': True,
            }
        )


def reverse_slots(apps, schema_editor):
    DeliverySlot = apps.get_model('orders', 'DeliverySlot')
    DeliverySlot.objects.filter(name__in=['Morning', 'Evening']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_deliveryslot'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RunPython(seed_default_slots, reverse_slots),
    ]
