# Generated by Django 6.0.6 on 2026-06-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_cartitem_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'verbose_name': 'Delivery Tracker (Orders)', 'verbose_name_plural': 'Delivery Tracker (Orders)'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID for online payments', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
    ]
