# Generated by Django 6.0.5 on 2026-06-29 08:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_deliveryorder_options_order_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryslot',
            name='order_start_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Orders placed FROM this time onwards get this slot. If start > cutoff, the range crosses midnight.'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot_ref',
            field=models.ForeignKey(blank=True, help_text='FK reference for robust slot querying — survives label renames', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryslot'),
        ),
        migrations.AlterField(
            model_name='deliverycluster',
            name='delivery_slot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryslot',
            name='delivery_end_time',
            field=models.TimeField(help_text='When delivery window closes'),
        ),
        migrations.AlterField(
            model_name='deliveryslot',
            name='delivery_start_time',
            field=models.TimeField(help_text='When delivery boy actually starts delivering'),
        ),
        migrations.AlterField(
            model_name='deliveryslot',
            name='order_cutoff_time',
            field=models.TimeField(help_text='Orders placed BEFORE this time get this slot.'),
        ),
        migrations.AlterField(
            model_name='deliveryslot',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text="Lower = processed first. Determines which slot is the 'first' (fallback after midnight)."),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
