# Generated by Django 6.0.6 on 2026-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderproduct_deliverycluster_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'OrderDetail Card', 'verbose_name_plural': 'OrderDetail Cards'},
        ),
        migrations.AddField(
            model_name='order',
            name='refund_id',
            field=models.CharField(blank=True, help_text='Razorpay refund ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, help_text='Refund status (e.g., PROCESSED, FAILED)', max_length=50, null=True),
        ),
    ]
