# Generated by Django 6.0.6 on 2026-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_orderproduct_options_order_refund_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Scheduler Lock',
                'verbose_name_plural': 'Scheduler Locks',
            },
        ),
    ]
