# Generated by Django 6.0.6 on 2026-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_schedulerlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test_order',
            field=models.BooleanField(default=False, help_text='Test order created via admin without sending notifications'),
        ),
    ]
