# Generated by Django 6.0.5 on 2026-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.AddField(
            model_name='slide',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
