# Generated by Django 6.0.5 on 2026-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_slide_image_slide_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
