# Generated by Django 6.0.5 on 2026-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_contactquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactquery',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
