# Generated by Django 6.0.5 on 2026-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_contactquery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=100.0, help_text='Orders above this amount get free delivery.', max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=50.0, help_text='Standard delivery charge for orders below the threshold.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
