# Generated by Django 6.0.5 on 2026-06-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g. 5, 12, 18)', max_digits=5),
        ),
    ]
