# Generated by Django 6.0.5 on 2026-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_slide_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, help_text='First button link (Shop Now)', max_length=500),
        ),
    ]
