# Generated by Django 6.0.5 on 2026-06-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order weight in kg. Leave 0.00 for no minimum.', max_digits=6),
        ),
    ]
