# Generated by Django 6.0.5 on 2026-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_min_order_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_order_weight',
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum multiple of the base unit required to order'),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum multiple of the base unit required to order'),
        ),
    ]
