# Generated by Django 6.0.5 on 2026-06-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_min_order_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='min_order_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order quantity (0 = no minimum, first click adds one step)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='order_step',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity step for +/- buttons (e.g. 1 for 1 piece/kg, 0.25 for 250g steps)', max_digits=6),
        ),
    ]
