# Generated by Django 6.0.5 on 2026-06-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_product_min_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='max_delivery_radius',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Maximum delivery radius in km. Orders beyond this distance will be blocked.', max_digits=5),
        ),
    ]
