# Generated by Django 6.0.5 on 2026-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_storesettings_max_delivery_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='announcement_bg_color',
            field=models.CharField(default='#0c831f', help_text='Background color of the banner (hex code or CSS color, e.g., #0c831f or red)', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_message',
            field=models.TextField(blank=True, help_text="Text to display in the announcement banner. e.g., 'We deliver vegetables from 7am to 12pm...'", null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_text_color',
            field=models.CharField(default='#ffffff', help_text='Text color of the banner (e.g., #ffffff or white)', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='is_announcement_active',
            field=models.BooleanField(default=False, help_text='Check this to display the announcement banner on the home page.'),
        ),
    ]
