# Generated by Django 6.0.6 on 2026-07-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_section_category_section_product_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='store.section'),
        ),
    ]
