# Generated by Django 6.0.6 on 2026-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_slide_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='product_label',
            field=models.CharField(blank=True, default='', help_text="Custom badge to show on all products in this section (e.g. 'Organic' or 'Keto')", max_length=50),
        ),
    ]
