# Generated by Django 6.0.6 on 2026-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_section_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='text_color',
            field=models.CharField(blank=True, help_text='Optional custom hex color for text, e.g. #FFFFFF or #1A1A1A', max_length=50, null=True),
        ),
    ]
