# Generated by Django 6.0.6 on 2026-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_slide_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='free_delivery_first_order',
            field=models.BooleanField(default=True, help_text="Enable free delivery for the user's first order."),
        ),
    ]
