# Generated by Django 6.0.6 on 2026-07-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_storesettings_free_delivery_first_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='free_dhaniya_threshold_kg',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum order weight in kg to get free dhaniya.', max_digits=5),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='is_free_dhaniya_active',
            field=models.BooleanField(default=False, help_text='Toggle free dhaniya offer on or off.'),
        ),
    ]
