# Generated by Django 6.0.6 on 2026-07-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_storesettings_free_dhaniya_threshold_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide product from the frontend without deleting it'),
        ),
    ]
