# Generated by Django 6.0.5 on 2026-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='admin_notification_email',
            field=models.EmailField(blank=True, help_text='Email address that receives detailed alerts for new orders. Leave blank to disable.', max_length=254, null=True),
        ),
    ]
