# Generated by Django 6.0.6 on 2026-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_storesettings_admin_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='admin_notification_phone',
            field=models.CharField(blank=True, help_text='Phone number to receive new order Push Notifications (User must have logged into the app at least once)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='admin_notification_email',
            field=models.EmailField(blank=True, help_text='Email address to receive new order alerts (e.g. admin@freshinbasket.com)', max_length=254, null=True),
        ),
    ]
