# Generated by Django 6.0.6 on 2026-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_storesettings_admin_notification_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='admin_notification_email',
            field=models.CharField(blank=True, help_text='Comma-separated emails to receive new order alerts (e.g. admin1@gmail.com, admin2@gmail.com)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='admin_notification_phone',
            field=models.CharField(blank=True, help_text='Comma-separated phone numbers to receive admin Push Notifications (e.g. 9876543210, 9123456789)', max_length=500, null=True),
        ),
    ]
