# Generated by Django 6.0.5 on 2026-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_storesettings_admin_notification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='subproducts/'),
        ),
    ]
