# Generated by Django 6.0.6 on 2026-06-20 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='please enter a valid 10-digit phone number', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Username may contain letters, numbers, spaces, underscores, and hyphens.', regex='^[\\w\\s\\-]*$')]),
        ),
    ]
