# Generated by Django 6.0.5 on 2026-06-25 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers_otpverification_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('max_orders', models.PositiveIntegerField(default=40)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
