# Generated by Django 6.0.6 on 2026-07-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_deliveryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery Boy',
                'verbose_name_plural': 'Delivery Boys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
